routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index')->name('index');

Auth::routes();

Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function () {
    Route::group(['middleware' => ['role:Admin']], function () {
        Route::resource('user', 'UserController');
        Route::match(['put', 'patch'], '/user/resetpassword/{id}', 'UserController@resetpassword')->name('user.resetpassword');
        Route::get('/user/{id}/reset', 'UserController@reset')->name('user.reset');
        Route::resource('place', 'PlaceController');
        Route::resource('product', 'ProductController');
        Route::resource('distributorproduct', 'DistributorProductController');
    });
    Route::group(['middleware' => ['role:Admin,Distributor']], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::get('/profil/{id}', 'ProfileController@index')->name('profile.index');
        Route::get('/profil/{id}/edit', 'ProfileController@edit')->name('profile.edit');
        Route::put('/profil/{id}/update', 'ProfileController@update')->name('profile.update');
        Route::match(['put', 'patch'], '/profile/resetpassword/{id}', 'ProfileController@resetpassword')->name('profile.resetpassword');
        Route::get('/profile/{id}/reset', 'ProfileController@reset')->name('profile.reset');
        Route::resource('transaction', 'TransactionController');
		Route::post('transaction/checkout', 'TransactionController@checkout')->name('transaction.checkout');
		Route::get('transaction/checkout', 'TransactionController@checkout');
    });
    Route::get('{any}', 'FrontController@any');
});

Route::get('{any}', 'FrontController@any');

app/Http/Controllers/DistributorProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Alert;
use App\Model\Product;
use App\Model\Distributor;

class DistributorProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderBy('updated_at', 'DESC')->get();
        $distributors = Distributor::whereHas('user', function ($query) {
            $query->orderBy('name', 'DESC');
        })->get();

        return view('distributorproduct.index', compact('products', 'distributors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $products = Product::orderBy('title', 'DESC')->get();
        $distributor = Distributor::whereHas('user', function ($query) {
            $query->orderBy('name', 'DESC');
        })->find($id);
        return view('distributorproduct.edit', compact('products', 'distributor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $distributor = Distributor::find($id);

        $stock = 0;
        foreach ($request->stock as $value) {
            $stock += $value;
        }
        if($distributor->capacity < $stock) {
            return redirect()->back()->withErrors(['Produk yang ingin direstock melebihi kapasitas gudang!', 'msg']);
        }
        else {
            for ($i=0; $i < count($request->product_id); $i++) { 
                $data[$request->product_id[$i]] = ['stock' => $request->stock[$i]];
            }
            $distributor->product()->sync($data);
            Alert::success('Data berhasil disimpan!', 'Sukses');
            return redirect()->route('distributorproduct.index');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/distributorproduct/edit.blade.php
@section('title')
    Data Produk Distributor
@endsection
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
             <form action="{{ route('distributorproduct.update', $distributor->id) }}" method="post" enctype="multipart/form-data">
                {{ method_field('put') }}
                {{ csrf_field() }}
                <div class="card-header">
                    <div class="card-title">Form Ubah Data Produk {{ $distributor->user->name }}</div>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="product_id">Produk untuk Distributor</label>
                        @foreach ($products as $product)
                        <div class="form-inline my-2">
                            <div class="form-check p-0 mr-4">
                                <label class="form-check-label">
                                    <input class="form-check-input" type="checkbox" name="product_id[]" value="{{ $product->id }}" @if ($distributor->product->contains($product->id)) checked @endif>
                                    <span class="form-check-sign">{{ $product->title }}</span>
                                </label>
                            </div>
                            @if ($distributor->product->contains($product->id))
                                @foreach ($product->distributor as $item)
                                    @if ($item->pivot->distributor_id == $distributor->id)
                                        <div class="stock">
                                            <input type="number" class="form-control form-control-sm col-5" name="stock[]" value="{{ $item->pivot->stock }}">
                                        </div>
                                    @endif
                                @endforeach
                            @else 
                            <div class="stock" style="display:none;"></div>
                            @endif
                        </div>
                        @endforeach
                        @if($errors->any())
                            <span class="form-text text-danger">
                                {{$errors->first()}}
                            </span>
                        @endif
                    </div>
                </div>
                <div class="card-action">
                    <button class="btn btn-success" type="submit">Simpan</button>
                    <a href="{{ route('distributorproduct.index') }}" class="btn btn-danger">Batal</a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('js')
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    jQuery('#preview').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }
        $('input[type=checkbox]').each(function () {
            $(this).click(function() {
                $(this).closest('div').next().toggle();
            });
        });
        $('input[type=checkbox]').change(function () {
            if ($(this).is(':checked')) {
                $(this).closest('div').next().append('<input type="number" class="form-control form-control-sm col-5" name="stock[]">');
            }
            else {
                $(this).closest('div').next().find('.form-control-sm').remove();
            } 
        });
    </script>
@endsection

resources/views/distributorproduct/index.blade.php
@section('title')
    Data Produk Distributor
@endsection

@extends('layouts.app')

@section('content')
{{-- <div class="mb-4">
    <a href="{{ route('distributor.create') }}">
        <button type="button" class="btn btn-info">Tambah Data</button>
    </a>
</div> --}}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Tabel @yield('title')</div>
            </div>
            <div class="card-body">
                <table class="table table-bordered table-head-bg-info table-bordered-bd-info">
                    <thead>
                        <tr>
                            <th width="30">No.</th>
                            <th>Nama Distributor</th>
                            <th>Kapasitas Gudang</th>
                            <th>Jumlah Produk di Gudang</th>
                            <th width="100">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($distributors as $index => $distributor)
                            <tr>
                                <td>{{ $index+1 }}</td>
                                <td>{{ $distributor->user->name }}</td>
                                <td>{{ $distributor->capacity }}</td>
                                <td>
                                    @if ($distributor->product->isEmpty())
                                        0
                                    @else
                                        {{ $distributor->product()->get()->sum('pivot.stock') }}
                                    @endif
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <a href="{{ route('user.show', $distributor->user->id . "#product") }}" class="btn btn-primary px-2 py-1">
                                            <i class="la la-eye"></i>
                                        </a>
                                        {{-- <a href="{{ route('distributor.edit', $distributor->id) }}" class="btn btn-success px-2 py-1 ml-1">
                                            <i class="la la-pencil-square"></i>
                                        </a> --}}
                                        <a href="{{ route('distributorproduct.edit', $distributor->id) }}" class="btn btn-warning px-2 py-1 ml-1">
                                            {{-- <i class="fas fa-warehouse-square"></i> --}}
                                            <i class="las la-warehouse"></i>
                                        </a>
                                        <form action="{{ route('distributorproduct.destroy', $distributor->id) }}" method="post">
                                        {{ csrf_field() }}
                                        {{ method_field('delete') }}
                                            <button class="btn btn-danger px-2 py-1 ml-1" onclick="return confirm('Anda yakin ingin menghapus data ini?')"> 
                                                <i class="la la-trash"></i>
                                            </button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@section('css')
    <link rel="stylesheet" href="{{ asset('assets/css/plugin/datatable/dataTables.bootstrap4.min.css') }}">
@endsection

@section('js')
    <script src="{{ asset('assets/js/plugin/datatable/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/js/plugin/datatable/dataTables.bootstrap4.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $("table.table-head-bg-info").DataTable({
                "oLanguage": {
                    "sLengthMenu": "Tampilkan _MENU_ distributor",
                    "sZeroRecords": "Belum ada distributor apapun",
                    "sInfoEmpty": "Menampilkan 0 data",
                    "sInfoFiltered": "",
                    "sInfo": "Menampilkan _START_ - _END_ dari _TOTAL_ distributor",
                    "sSearch": "Cari: ",
                    "oPaginate": {
                        "sNext": "Selanjutnya",
                        "sPrevious": "Sebelumnya",
                    }
                },
                stateSave: true
            });
        });
    </script>
@endsection