routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index')->name('index');

Auth::routes();

Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function () {
    Route::group(['middleware' => ['role:Admin']], function () {
        Route::resource('user', 'UserController');
        Route::match(['put', 'patch'], '/user/resetpassword/{id}', 'UserController@resetpassword')->name('user.resetpassword');
        Route::get('/user/{id}/reset', 'UserController@reset')->name('user.reset');
        Route::resource('place', 'PlaceController');
        Route::resource('product', 'ProductController');
        Route::resource('distributorproduct', 'DistributorProductController');
    });
    Route::group(['middleware' => ['role:Admin,Distributor']], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::get('/profil/{id}', 'ProfileController@index')->name('profile.index');
        Route::get('/profil/{id}/edit', 'ProfileController@edit')->name('profile.edit');
        Route::put('/profil/{id}/update', 'ProfileController@update')->name('profile.update');
        Route::match(['put', 'patch'], '/profile/resetpassword/{id}', 'ProfileController@resetpassword')->name('profile.resetpassword');
        Route::get('/profile/{id}/reset', 'ProfileController@reset')->name('profile.reset');
        Route::resource('transaction', 'TransactionController');
		Route::post('transaction/checkout', 'TransactionController@checkout')->name('transaction.checkout');
		Route::get('transaction/checkout', 'TransactionController@checkout');
    });
    Route::get('{any}', 'FrontController@any');
});

Route::get('{any}', 'FrontController@any');

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Alert;
use Carbon\Carbon;
use App\Model\Product;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderBy('updated_at', 'DESC')->get();
        return view('product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'title' => 'required',
            'description' => 'required',
            'price' => 'required',
            'image' => 'max:3000|mimes:jpg,jpeg,png'
        ];

        $rulesMessages = [
            'required' => 'Wajib diisi!',
            'max' => 'Maksimal file 3MB!',
            'mimes' => 'Format harus jpg, jpeg, png!'
        ];

        $this->validate($request, $rules, $rulesMessages);

        $data = [
            'id' => (string) Str::uuid(),
            'title' => $request->title,
            'description' => $request->description,
            'price' => $request->price
        ];

        if ($request->hasFile("image")) {
            $name = Carbon::now()->format('d_m_Y') . "_" . mt_rand(0001, 9999);
            $image = $request->image;
            $image_name = "product_" . $name . '.' . $image->getClientOriginalExtension();
            $image->storeAs('public/product/', $image_name);
            $data['image'] = (string) $image_name;
        } 
        else {
            $data['image'] = null;
        }
        Product::create($data);

        Alert::success('Data berhasil disimpan!', 'Sukses');
        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);
        return view('product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        return view('product.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'title' => 'required',
            'description' => 'required',
            'price' => 'required',
            'image' => 'max:3000|mimes:jpg,jpeg,png'
        ];

        $rulesMessages = [
            'required' => 'Wajib diisi!',
            'max' => 'Maksimal file 3MB!',
            'mimes' => 'Format harus jpg, jpeg, png!'
        ];

        $this->validate($request, $rules, $rulesMessages);

        $product = Product::find($id);

        $data = [
            'title' => $request->title,
            'description' => $request->description,
            'price' => $request->price
        ];

        if ($request->hasFile("image")) {
            $image_path = public_path("storage/product/" . $product->image);
            if (is_file($image_path)) {
                unlink($image_path);
            }
            $name = Carbon::now()->format('d_m_Y') . "_" . mt_rand(0001, 9999);
            $image = $request->image;
            $image_name = "product_" . $name . '.' . $image->getClientOriginalExtension();
            $image->storeAs('public/product/', $image_name);
            $data['image'] = (string) $image_name;
        }
        $product->update($data);

        Alert::success('Data berhasil diubah!', 'Sukses');
        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        $product->delete();

        Alert::success('Data berhasil dihapus!', 'Sukses');
        return redirect()->route('product.index');
    }
}

resources/views/product/create.blade.php
@section('title')
    Data Produk
@endsection
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <form action="{{ route('product.store') }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="card-header">
                    <div class="card-title">Form Tambah @yield('title')</div>
                </div>
                <div class="card-body">
                    <div class="form-group @error('title') has-error @enderror">
                        <label for="title">Judul Produk</label>
                        <input type="text" class="form-control" id="title" name="title" placeholder="contoh: hijab sport" value="{{ old('title') }}" required>
                        @error('title')
                            <span class="form-text text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                    <div class="form-group @error('description') has-error @enderror">
                        <label for="description">Deskripsi Produk</label>
                        <textarea name="description" id="description" cols="30" rows="5" class="form-control" placeholder="contoh: produk ini recommended" required>{{ old('description') }}</textarea>
                        @error('description')
                            <span class="form-text text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                     <div class="form-group @error('price') has-error @enderror">
                        <label for="price">Harga Produk</label>
                        <input type="number" class="form-control" name="price" id="price" value="{{ old('price') }}" required>
                        @error('price')
                            <span class="form-text text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                    <div class="form-group pb-0">
                        <label for="image">Gambar Produk</label>
                    </div>
                    <div class="form-group @error('image') has-error @enderror pt-0">
                        <img id="preview" height="150" width="150" src="{{ asset('assets/images/nopic.jpg') }}">
                        <input type="file" class="form-control mt-2" id="image" name="image" onchange="readURL(this);">
                        @error('image')
                            <span class="form-text text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="card-action">
                    <button class="btn btn-success" type="submit">Simpan</button>
                    <a href="{{ route('product.index') }}" class="btn btn-danger">Batal</a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('js')
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    jQuery('#preview').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
@endsection

resources/views/product/edit.blade.php
@section('title')
    Data Produk
@endsection
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
             <form action="{{ route('product.update', $product->id) }}" method="post" enctype="multipart/form-data">
                {{ method_field('put') }}
                {{ csrf_field() }}
                <div class="card-header">
                    <div class="card-title">Form Ubah @yield('title') {{ $product->title }}</div>
                </div>
                <div class="card-body">
                    <div class="form-group @error('title') has-error @enderror">
                        <label for="title">Judul Produk</label>
                        <input type="text" class="form-control" id="title" name="title" placeholder="contoh: hijab sport" value="{{ $product->title }}" required>
                        @error('title')
                            <span class="form-text text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                    <div class="form-group @error('description') has-error @enderror">
                        <label for="description">Deskripsi Produk</label>
                        <textarea name="description" id="description" cols="30" rows="5" class="form-control" placeholder="contoh: produk ini recommended" required>{{ $product->description }}</textarea>
                        @error('description')
                            <span class="form-text text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                     <div class="form-group @error('price') has-error @enderror">
                        <label for="price">Harga Produk</label>
                        <input type="number" class="form-control" name="price" id="price" value="{{ $product->price }}" required>
                        @error('price')
                            <span class="form-text text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                    <div class="form-group pb-0">
                        <label for="image">Gambar Produk</label>
                    </div>
                    <div class="form-group @error('image') has-error @enderror pt-0">
                        @if($product->image)
                            @if(file_exists(public_path(). '/storage/product/'. $product->image))
                                <img id="preview" height="150" width="150" src="{{asset('storage/product/'. $product->image)}}">
                            @else
                                <img id="preview" height="150" width="150" src="{{ asset('assets/images/nopic.jpg') }}">
                            @endif
                        @else
                            <img id="preview" height="150" width="150" src="{{ asset('assets/images/nopic.jpg') }}">
                        @endif
                        <input type="file" class="form-control mt-2" id="image" name="image" onchange="readURL(this);">
                        @error('image')
                            <span class="form-text text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="card-action">
                    <button class="btn btn-success" type="submit">Simpan</button>
                    <a href="{{ route('product.index') }}" class="btn btn-danger">Batal</a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('js')
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    jQuery('#preview').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
@endsection

resources/views/product/index.blade.php
@section('title')
    Data Produk
@endsection

@extends('layouts.app')

@section('content')
<div class="mb-4">
    <a href="{{ route('product.create') }}">
        <button type="button" class="btn btn-info">Tambah Data</button>
    </a>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Tabel @yield('title')</div>
            </div>
            <div class="card-body">
                <table id="productTable" class="table table-bordered table-head-bg-info table-bordered-bd-info">
                    <thead>
                        <tr>
                            <th width="30">No.</th>
                            <th>Judul Produk</th>
                            <th>Harga</th>
                            <th>Jumlah Distributor</th>
                            <th>Total Penjualan</th>
                            <th width="100">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($products as $index => $product)
                            <tr>
                                <td>{{ $index+1 }}</td>
                                <td>{{ $product->title }}</td>
                                <td>Rp. {{ number_format($product->price, 2, ',', '.') }}</td>
                                <td>{{ $product->distributor->count() }}</td>
                                <td>{{ $product->transaction->count() }}</td>
                                <td>
                                    <div class="btn-group">
                                        <a href="{{ route('product.show', $product->id) }}" class="btn btn-primary px-2 py-1">
                                            <i class="la la-eye"></i>
                                        </a>
                                        <a href="{{ route('product.edit', $product->id) }}" class="btn btn-success px-2 py-1 mx-2">
                                            <i class="la la-pencil-square"></i>
                                        </a>
                                        <form action="{{ route('product.destroy', $product->id) }}" method="post">
                                        {{ csrf_field() }}
                                        {{ method_field('delete') }}
                                            <button class="btn btn-danger px-2 py-1" onclick="return confirm('Anda yakin ingin menghapus data ini?')"> 
                                                <i class="la la-trash"></i>
                                            </button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@section('css')
    <link rel="stylesheet" href="{{ asset('assets/css/plugin/datatable/dataTables.bootstrap4.min.css') }}">
@endsection

@section('js')
    <script src="{{ asset('assets/js/plugin/datatable/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/js/plugin/datatable/dataTables.bootstrap4.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $("#productTable").DataTable({
                "oLanguage": {
                    "sLengthMenu": "Tampilkan _MENU_ produk",
                    "sZeroRecords": "Belum ada produk apapun",
                    "sInfoEmpty": "Menampilkan 0 data",
                    "sInfoFiltered": "",
                    "sInfo": "Menampilkan _START_ - _END_ dari _TOTAL_ produk",
                    "sSearch": "Cari: ",
                    "oPaginate": {
                        "sNext": "Selanjutnya",
                        "sPrevious": "Sebelumnya",
                    }
                },
                stateSave: true
            });
        });
    </script>
@endsection

resources/views/product/show.blade.php
@section('title')
    Data Produk
@endsection
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Rincian Produk {{ $product->title }}</div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-7">
                        <div>
                            <p>
                                <span class="font-weight-bold">Nama Produk : </span> {{ $product->title }}
                            </p>
                            <p>
                                <span class="font-weight-bold">Harga : </span> Rp. {{ number_format($product->price, 2, ',', '.') }}
                            </p>
                            <p>
                                <span class="font-weight-bold">Deskripsi Produk : </span> {{ $product->description }}
                            </p>
                        </div>
                        <hr>
                        <div>
                            <p class="font-weight-bold">
                                Jumlah Distributor : {{ $product->distributor->count() }}
                            </p>
                            <p class="font-weight-bold">
                                Daftar Nama Distributor Produk {{ $product->city }} :
                            </p>
                            @if (!$product->distributor->isEmpty())
                                <ol>
                                    @foreach ($product->distributor as $distributor)
                                        <li>{{ $distributor->user->name }} ({{ $distributor->place->city }})</li>
                                    @endforeach
                                </ol> 
                            @else 
                                <p>Belum ada distributor</p>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-5">
                        @if($product->image)
                            @if(file_exists(public_path(). '/storage/product/'. $product->image))
                                <img src="{{asset('storage/product/'. $product->image)}}" width="350" alt="image" style="margin-right: 10px;" />
                            @else
                                <img src="{{asset('assets/images/nopic.jpg')}}" width="350" alt="image" style="margin-right: 10px;" /> 
                            @endif
                        @else
                            <img src="{{asset('assets/images/nopic.jpg')}}" width="350" alt="image" style="margin-right: 10px;" /> 
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection