routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index')->name('index');

Auth::routes();

Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function () {
    Route::group(['middleware' => ['role:Admin']], function () {
        Route::resource('user', 'UserController');
        Route::match(['put', 'patch'], '/user/resetpassword/{id}', 'UserController@resetpassword')->name('user.resetpassword');
        Route::get('/user/{id}/reset', 'UserController@reset')->name('user.reset');
        Route::resource('place', 'PlaceController');
        Route::resource('product', 'ProductController');
        Route::resource('distributorproduct', 'DistributorProductController');
    });
    Route::group(['middleware' => ['role:Admin,Distributor']], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::get('/profil/{id}', 'ProfileController@index')->name('profile.index');
        Route::get('/profil/{id}/edit', 'ProfileController@edit')->name('profile.edit');
        Route::put('/profil/{id}/update', 'ProfileController@update')->name('profile.update');
        Route::match(['put', 'patch'], '/profile/resetpassword/{id}', 'ProfileController@resetpassword')->name('profile.resetpassword');
        Route::get('/profile/{id}/reset', 'ProfileController@reset')->name('profile.reset');
        Route::resource('transaction', 'TransactionController');
		Route::post('transaction/checkout', 'TransactionController@checkout')->name('transaction.checkout');
		Route::get('transaction/checkout', 'TransactionController@checkout');
    });
    Route::get('{any}', 'FrontController@any');
});

Route::get('{any}', 'FrontController@any');

app/Http/Controllers/PlaceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Alert;
use Mapper;
use App\Model\Place;
use App\Model\Distributor;

class PlaceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $places = Place::orderBy('updated_at', 'DESC')->get();
        $distributors = Distributor::all();
        Mapper::location('Jawa Timur')->map(
        [
            'zoom' => 8, 
            'center' => true, 
            'marker' => false
        ]);
        return view('place.index', compact('places'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('place.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'city' => 'required'
        ];

        $rulesMessages = [
            'required' => 'Wajib diisi!'
        ];

        $this->validate($request, $rules, $rulesMessages);

        $data = [
            'id' => (string) Str::uuid(),
            'city' => $request->city
        ];
        Place::create($data);

        Alert::success('Data berhasil disimpan!', 'Sukses');
        return redirect()->route('place.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $place = Place::find($id);
        $distributors = Distributor::where('place_id', $place->id)->get();
        Mapper::location($place->city)->map(
        [
            'zoom' => 11, 
            'center' => true, 
            'marker' => false
        ]);
        foreach ($distributors as $index => $distributor) {
            $content = "<br>Nama Distributor: " . $distributor->user->name . "<br>Alamat: " . $distributor->address . "<br><br><a href='/dashboard/user/" . $distributor->user->id . "' class='btn btn-primary px-2 py-1'>Lihat Detail</a>";
            Mapper::informationWindow($distributor->coordinate->getLat(), $distributor->coordinate->getLng(), $content, 
            [ 
                'maxWidth' => 600,
            ]);
        }
        return view('place.show', compact('place', 'distributors'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $place = Place::find($id);
        return view('place.edit', compact('place'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'city' => 'required'
        ];

        $rulesMessages = [
            'required' => 'Wajib diisi!'
        ];

        $this->validate($request, $rules, $rulesMessages);

        $place = Place::find($id);

        $data = [
            'city' => $request->city
        ];
        $place->update($data);

        Alert::success('Data berhasil diubah!', 'Sukses');
        return redirect()->route('place.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $place = Place::find($id);
        $place->delete();

        Alert::success('Data berhasil dihapus!', 'Sukses');
        return redirect()->route('place.index');
    }
}

resources/views/place/create.blade.php
@section('title')
    Data Kota Distributor
@endsection
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12 stretch-card">
        <div class="card">
            <form action="{{ route('place.store') }}" method="post">
                {{ csrf_field() }}
                <div class="card-header">
                    <div class="card-title">Form Tambah @yield('title')</div>
                </div>
                <div class="card-body">
                    <div class="form-group @error('city') has-error @enderror">
                        <label for="city">Nama Kota</label>
                        <input type="text" class="form-control" id="city" name="city" placeholder="contoh: surabaya" value="{{ old('city') }}" required>
                        @error('city')
                            <span class="form-text text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="card-action">
                    <button class="btn btn-success" type="submit">Simpan</button>
                    <a href="{{ route('place.index') }}" class="btn btn-danger">Batal</a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/place/edit.blade.php
@section('title')
    Data Kota Distributor
@endsection
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12 stretch-card">
        <div class="card">
            <form action="{{ route('place.update', $place->id) }}" method="post">
                {{ method_field('put') }}
                {{ csrf_field() }}
                <div class="card-header">
                    <div class="card-title">Form Ubah Kota {{ $place->city }}</div>
                </div>
                <div class="card-body">
                    <div class="form-group @error('city') has-error @enderror">
                        <label for="city">Nama Kota</label>
                        <input type="text" class="form-control" id="city" name="city" placeholder="contoh: surabaya" value="{{ $place->city }}" required>
                        @error('city')
                            <span class="form-text text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="card-action">
                    <button class="btn btn-success" type="submit">Simpan</button>
                    <a href="{{ route('place.index') }}" class="btn btn-danger">Batal</a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/place/index.blade.php
@section('title')
    Data Kota Distributor
@endsection

@extends('layouts.app')

@section('content')
<div class="mb-4">
    <a href="{{ route('place.create') }}">
        <button type="button" class="btn btn-info">Tambah Data</button>
    </a>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Tabel @yield('title')</div>
            </div>
            <div class="card-body">
                <table id="placeTable" class="table table-bordered table-head-bg-info table-bordered-bd-info">
                    <thead>
                        <tr>
                            <th width="30">No.</th>
                            <th>Kota</th>
                            <th>Jumlah Distributor</th>
                            <th width="100">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($places as $index => $place)
                            <tr>
                                <td>{{ $index+1 }}</td>
                                <td>{{ $place->city }}</td>
                                <td>{{ $place->distributor->count() }}</td>
                                <td>
                                    <div class="btn-group">
                                        <a href="{{ route('place.show', $place->id) }}" class="btn btn-primary px-2 py-1">
                                            <i class="la la-eye"></i>
                                        </a>
                                        <a href="{{ route('place.edit', $place->id) }}" class="btn btn-success px-2 py-1 mx-2">
                                            <i class="la la-pencil-square"></i>
                                        </a>
                                        <form action="{{ route('place.destroy', $place->id) }}" method="post">
                                        {{ csrf_field() }}
                                        {{ method_field('delete') }}
                                            <button class="btn btn-danger px-2 py-1" onclick="return confirm('Anda yakin ingin menghapus data ini?')"> 
                                                <i class="la la-trash"></i>
                                            </button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Sebaran Distributor di Jawa Timur</div>
            </div>
            <div class="card-body">
                <div style="width: 100%; height: 350px;">
                    {!! Mapper::render() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('css')
    <link rel="stylesheet" href="{{ asset('assets/css/plugin/datatable/dataTables.bootstrap4.min.css') }}">
@endsection

@section('js')
    <script src="{{asset('jatim.geojson')}}" type="text/javascript"></script>
    <script src="{{ asset('assets/js/plugin/datatable/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/js/plugin/datatable/dataTables.bootstrap4.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $("#placeTable").DataTable({
                "oLanguage": {
                    "sLengthMenu": "Tampilkan _MENU_ kota",
                    "sZeroRecords": "Belum ada kota apapun",
                    "sInfoEmpty": "Menampilkan 0 data",
                    "sInfoFiltered": "",
                    "sInfo": "Menampilkan _START_ - _END_ dari _TOTAL_ kota",
                    "sSearch": "Cari: ",
                    "oPaginate": {
                        "sNext": "Selanjutnya",
                        "sPrevious": "Sebelumnya",
                    }
                },
                stateSave: true
            });
            function initMap() {
                var places = {!! json_encode($places->toArray(), JSON_HEX_TAG) !!};
                var geo = maps[0].map.data;
                geo.addGeoJson(jatim);
                geo.setStyle(function(feature) {  
                    var KABKOT = feature.getProperty('KABKOT');
                    var color = "gray";
                    places.forEach(element => {
                        if (element.distributor.length > 0) {
                            if (KABKOT == element.city) {
                                color = "yellow";
                            }
                        }
                        if (element.distributor.length < 1) {
                            if (KABKOT == element.city) {
                                color = "red";
                            }
                        }
                    });
                    return {
                        fillColor: color,
                        strokeWeight: 1
                    }
                });
                var infowindow = new google.maps.InfoWindow();
                geo.addListener('click', function(data_mouseEvent) {
                    var feature = data_mouseEvent.feature;
                    feature.toGeoJson(function(geojson){
                        var name = geojson.properties.KABKOT;
                        places.forEach(element => {
                            if (name == element.city) {
                                var distributor = element.distributor.length;
                                var myHTMLss = 'Kota: '+ name + '<br>' +
                                'Jumlah Distributor: '+ element.distributor.length + '<br>' +
                                "<a href='/dashboard/place/" + element.id + "' class='btn btn-primary px-2 py-1'>Lihat Detail</a>";
                                infowindow.setContent(myHTMLss);
                                infowindow.setPosition(data_mouseEvent.latLng);
                                infowindow.open(maps[0].map);
                            }
                        });
                    });
                });
            }
            google.maps.event.addDomListener(window, 'load', initMap);
        });
    </script>
@endsection

resources/views/place/show.blade.php
@section('title')
    Data Kota Distributor
@endsection
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Rincian Distribusi Produk di Kota {{ $place->city }}</div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div>
                            <p class="font-weight-bold">
                                Jumlah Distributor : {{ $place->distributor->count() }}
                            </p>
                        </div>
                        <hr>
                        <div>
                            <p class="font-weight-bold">
                                Daftar Nama Distributor di {{ $place->city }} :
                            </p>
                            @if (!$distributors->isEmpty())
                                <ol>
                                    @foreach ($distributors as $distributor)
                                    <li>{{ $distributor->user->name }} (target penjualan: {{ $distributor->capacity }}/bulan)</li>
                                    @endforeach
                                </ol> 
                            @else 
                                <p>Belum ada distributor</p>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-6 pull-right">
                        <p class="font-weight-bold">Lokasi pada Peta</p>
                        <div style="width: 100%; height: 350px;">
                            {!! Mapper::render() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection