routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index')->name('index');

Auth::routes();

Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function () {
    Route::group(['middleware' => ['role:Admin']], function () {
        Route::resource('user', 'UserController');
        Route::match(['put', 'patch'], '/user/resetpassword/{id}', 'UserController@resetpassword')->name('user.resetpassword');
        Route::get('/user/{id}/reset', 'UserController@reset')->name('user.reset');
        Route::resource('place', 'PlaceController');
        Route::resource('product', 'ProductController');
        Route::resource('distributorproduct', 'DistributorProductController');
    });
    Route::group(['middleware' => ['role:Admin,Distributor']], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::get('/profil/{id}', 'ProfileController@index')->name('profile.index');
        Route::get('/profil/{id}/edit', 'ProfileController@edit')->name('profile.edit');
        Route::put('/profil/{id}/update', 'ProfileController@update')->name('profile.update');
        Route::match(['put', 'patch'], '/profile/resetpassword/{id}', 'ProfileController@resetpassword')->name('profile.resetpassword');
        Route::get('/profile/{id}/reset', 'ProfileController@reset')->name('profile.reset');
        Route::resource('transaction', 'TransactionController');
		Route::post('transaction/checkout', 'TransactionController@checkout')->name('transaction.checkout');
		Route::get('transaction/checkout', 'TransactionController@checkout');
    });
    Route::get('{any}', 'FrontController@any');
});

Route::get('{any}', 'FrontController@any');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
    
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>DNY Hijab Sport WebGIS</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <link rel="shortcut icon" href="{{asset('assets/images/favicon.ico')}}" />
	<link rel="stylesheet" href="{{ asset('assets/css/bootstrap.min.css') }}">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
	<link rel="stylesheet" href="{{ asset('assets/css/ready.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/demo.css') }}">
    <link rel="stylesheet" href="{{ asset('line-awesome/css/line-awesome.min.css') }}">
    @yield('css')
</head>

<body>
    @auth
	<div class="wrapper">
		<div class="main-header">
			@include('layouts.navbar')
        </div>
        <div class="sidebar">
            @include('layouts.sidebar')
        </div>
        <div class="main-panel">
            <div class="content">
                <div class="container-fluid">
                    <h4 class="page-title">@yield('title')</h4>
                    @yield('content')
                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    @include('layouts.footer')			
                </div>
            </footer>
        </div>
	</div>
    @endauth
    @guest
            <div class="content">
                <div class="container-fluid">
                    {{-- <h4 class="page-title">@yield('title')</h4> --}}
                    @yield('content')
                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    @include('layouts.footer')			
                </div>
            </footer>
    @endguest
</body>

<script src="{{ asset('assets/js/core/jquery.3.2.1.min.js') }}"></script>
<script src="{{ asset('assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js') }}"></script>
<script src="{{ asset('assets/js/core/popper.min.js') }}"></script>
<script src="{{ asset('assets/js/core/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js') }}"></script>
<script src="{{ asset('assets/js/ready.min.js') }}"></script>
<script src="{{ asset('assets/js/demo.js') }}"></script>
<script src="{{asset('assets/js/plugin/sweetalert2.all.js')}}"></script>
@include('sweet::alert')
@yield('js')

</html>

resources/views/layouts/footer.blade.php
<nav class="pull-left">
    <span>Sistem Informasi Geografis Distributor DNY Hijab Sport</span>
</nav>
<div class="copyright ml-auto">
    2019, made with <i class="la la-heart heart text-danger"></i> by Rama & Ringgi
</div>	

resources/views/layouts/navbar.blade.php
<div class="logo-header">
    <a href="index.html" class="logo">
        DNY HIJAB SPORT
    </a>
    <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <button class="topbar-toggler more"><i class="la la-ellipsis-v"></i></button>
</div>
<nav class="navbar navbar-header navbar-expand-lg">
    <div class="container-fluid">
        @if (Auth::user()->role == 'Distributor')
        <ul class="navbar-nav">
            <li class="nav-item dropdown d-none d-lg-flex">
                <a href="{{ route('transaction.create') }}" class="nav-link nav-btn">
                    <span class="btn btn-info btn-round">+ Buat Transaksi</span>
                </a>
            </li>
        </ul>
        @endif
        <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
            <li class="nav-item dropdown">
                <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
                    @if(Auth::user()->photo!=null)
                        @if(file_exists(public_path(). '/storage/user/'. Auth::user()->photo))
                            <img src="{{ asset('storage/user/'. Auth::user()->photo) }}" alt="user-img" width="30" height="30" class="img-circle">
                        @else
                            <img src="{{ asset('assets/images/nopic.jpg') }}" alt="user-img" width="30" height="30" class="img-circle"> 
                        @endif
                    @else
                        <img src="{{ asset('assets/images/nopic.jpg') }}" alt="user-img" width="30" height="30" class="img-circle">
                    @endif
                    <span>{{ Auth::user()->name }}</span>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li>
                        <div class="user-box">
                            <div class="u-text">
                                <h4>{{ Auth::user()->name }}</h4>
                                <p class="text-muted">{{ Auth::user()->email }}</p>
                                @if (Auth::user()->role == 'Distributor')
                                    <a href="{{ route('profile.index', Auth::user()->id) }}" class="btn btn-rounded btn-danger btn-sm">Lihat Profil</a>
                                @endif
                            </div>
                        </div>
                    </li>
                    <div class="dropdown-divider"></div>
                    @if (Auth::user()->role == 'Admin')
                        <a class="dropdown-item" href="{{ route('user.edit', Auth::user()->id) }}"><i class="ti-user"></i> Ubah Profil</a>
                        <a class="dropdown-item" href="{{ route('user.reset', Auth::user()->id) }}"><i class="ti-user"></i> Ubah Password</a>
                    @endif
                    @if (Auth::user()->role == 'Distributor')
                        <a class="dropdown-item" href="{{ route('profile.index', Auth::user()->id . "#about") }}"><i class="ti-user"></i> Profil Saya</a>
                        <a class="dropdown-item" href="{{ route('profile.index', Auth::user()->id . "#product") }}"><i class="ti-user"></i> Stok Produk</a>
                        <a class="dropdown-item" href="{{ route('profile.index', Auth::user()->id . "#transaction") }}"><i class="ti-user"></i> Riwayat Transaksi</a>
                    @endif
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                        Keluar
                    </a>
                </ul>
            </li>
        </ul>
    </div>
</nav>

resources/views/layouts/sidebar.blade.php
<div class="scrollbar-inner sidebar-wrapper">
    <div class="user">
        <div class="photo">
            @if(Auth::user()->photo!=null)
                @if(file_exists(public_path(). '/storage/user/'. Auth::user()->photo))
                    <img src="{{ asset('storage/user/'. Auth::user()->photo) }}" alt="user-img">
                @else
                    <img src="{{ asset('assets/images/nopic.jpg') }}" alt="user-img"> 
                @endif
            @else
                <img src="{{ asset('assets/images/nopic.jpg') }}" alt="user-img">
            @endif
        </div>
        <div class="info">
            <a class="" data-toggle="collapse" href="#collapseExample" aria-expanded="true">
                <span>
                    {{ Auth::user()->name }}
                    <span class="user-level">{{ Auth::user()->role }}</span>
                    <span class="caret"></span>
                </span>
            </a>
            <div class="clearfix"></div>
            <div class="collapse in" id="collapseExample" aria-expanded="true" style="">
                <ul class="nav">
                    @if (Auth::user()->role == 'Distributor')
                        <li>
                            <a href="{{ route('profile.index', Auth::user()->id . "#about") }}">
                                <span class="link-collapse">Profil Saya</span>
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('profile.index', Auth::user()->id . "#product") }}">
                                <span class="link-collapse">Stok Produk</span>
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('profile.index', Auth::user()->id . "#transaction") }}">
                                <span class="link-collapse">Riwayat Transaksi</span>
                            </a>
                        </li>
                    @endif
                    @if (Auth::user()->role == 'Admin')
                        <li>
                            <a href="{{ route('user.edit', Auth::user()->id) }}">
                                <span class="link-collapse">Ubah Profil</span>
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('user.reset', Auth::user()->id) }}">
                                <span class="link-collapse">Ubah Password</span>
                            </a>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </div>
    <ul class="nav">
        <li class="nav-item {{ setActive(['dashboard']) }}">
            <a href="{{ route('dashboard') }}">
                <i class="la la-dashboard"></i>
                <p>Dashboard</p>
            </a>
        </li>
        @if(Auth::user()->role=='Distributor')
        <li class="nav-item {{ setActive(['transaction*']) }}">
            <a href="{{ route('transaction.index') }}">
                <i class="la la-comment"></i>
                <p>Riwayat Transaksi</p>
            </a>
        </li>
        @elseif(Auth::user()->role=='Admin')
        <li class="nav-item {{ setActive(['transaction*']) }}">
            <a href="{{ route('transaction.index') }}">
                <i class="la la-comment"></i>
                <p>Data Transaksi</p>
            </a>
        </li>
        <li class="nav-item {{ setActive(['place*']) }}">
            <a href="{{ route('place.index') }}">
                <i class="la la-cube"></i>
                <p>Data Kota Distributor</p>
            </a>
        </li>
        <li class="nav-item {{ setActive(['product*']) }}">
            <a href="{{ route('product.index') }}">
                <i class="la la-cube"></i>
                <p>Data Produk</p>
            </a>
        </li>
        <li class="nav-item {{ setActive(['distributorproduct*']) }}">
            <a href="{{ route('distributorproduct.index') }}">
                <i class="la la-cube"></i>
                <p>Data Produk Distributor</p>
            </a>
        </li>
        <li class="nav-item {{ setActive(['user*']) }}">
            <a href="{{ route('user.index') }}">
                <i class="la la-user"></i>
                <p>Data User</p>
            </a>
        </li>
        @endif
    </ul>
</div>